// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiqHv_WWMDgKqSVwqHVrN2MktH1UdlE04',
    appId: '1:159808517268:web:a8d8c07626c69f94c83081',
    messagingSenderId: '159808517268',
    projectId: 'solarencrypt-18c58',
    authDomain: 'solarencrypt-18c58.firebaseapp.com',
    storageBucket: 'solarencrypt-18c58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWLJ4Mj5iE4S1lwNVO7qv5vJFZ9WbafF4',
    appId: '1:159808517268:android:000667d9fd54284ac83081',
    messagingSenderId: '159808517268',
    projectId: 'solarencrypt-18c58',
    storageBucket: 'solarencrypt-18c58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnoytUJIypws_dX88OL7CjoeeTO5fgi30',
    appId: '1:159808517268:ios:aa8cd7957033aa19c83081',
    messagingSenderId: '159808517268',
    projectId: 'solarencrypt-18c58',
    storageBucket: 'solarencrypt-18c58.appspot.com',
    iosClientId: '159808517268-cpc12o8633vpaagdkuhpg9j656cu1ult.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarencrypt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnoytUJIypws_dX88OL7CjoeeTO5fgi30',
    appId: '1:159808517268:ios:161ff2afbaa81e79c83081',
    messagingSenderId: '159808517268',
    projectId: 'solarencrypt-18c58',
    storageBucket: 'solarencrypt-18c58.appspot.com',
    iosClientId: '159808517268-aicgq30l00n8bp9sbeulg48ng60ndql1.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarencrypt.RunnerTests',
  );
}
